name: "Shared Rust toolchain setting up steps"
description: "Shared Rust toolchain setting up steps"
inputs:
  rust_toolchain_version:
    description: "Rust toolchain version"
    required: true
  shell:
    description: "Shell to use"
    required: false
    default: "bash"
runs:
  using: "composite"
  steps:
    # As action-rs does not seem to be maintained anymore, building from
    # scratch the environment using rustup
    - name: Setup Rust toolchain ${{ inputs.rust_toolchain_version }}
      run: |
        curl --proto '=https' --tlsv1.2 -sSf -o rustup-init \
        https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
        chmod +x ./rustup-init
        ./rustup-init -y --default-toolchain "${{ inputs.rust_toolchain_version }}" --profile default
        rm ./rustup-init
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        # overwriting default rust-toolchain
        echo ${{ inputs.rust_toolchain_version }} > rust-toolchain
      shell: ${{ inputs.shell }}
