#
# This workflow is triggered nightly (or on-demand) to run all the tests with the code coverage enabled and using the self-hosted GitHub runner.
#

name: Nightly tests with code coverage

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

env:
  # https://doc.rust-lang.org/cargo/reference/profiles.html#release
  RUSTFLAGS: -Coverflow-checks=y -Cdebug-assertions=y
  # https://doc.rust-lang.org/cargo/reference/profiles.html#incremental
  CARGO_INCREMENTAL: 1
  # https://nexte.st/book/pre-built-binaries.html#using-nextest-in-github-actions
  CARGO_TERM_COLOR: always
  RUST_MIN_STACK: 31457280
  # 30 MB of stack for Keccak tests

jobs:
  run_tests:
    name: Run all tests with the code coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_toolchain_version: ["1.74"]
        # FIXME: currently not available for 5.0.0.
        # It might be related to boxroot dependency, and we would need to bump
        # up the ocaml-rs dependency
        ocaml_version: ["4.14"]
        os: ["hetzner-1"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Use shared Rust toolchain setting up steps
        uses: ./.github/actions/toolchain-shared
        with:
          rust_toolchain_version: ${{ matrix.rust_toolchain_version }}

      - name: Use shared OCaml setting up steps
        uses: ./.github/actions/ocaml-shared
        with:
          ocaml_version: ${{ matrix.ocaml_version }}

      - name: Install test dependencies
        run: |
          make install-test-deps

      - name: Run all tests with the code coverage
        run: |
          eval $(opam env)
          make clean
          make nextest-all-with-coverage

      - name: Use shared Codecov reporting steps
        uses: ./.github/actions/codecov-shared
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
