name: Deploy Specifications & Docs to GitHub Pages

on:
  push:
    branches:
      - master

env:
  OCAML_VERSION: "4.14.0"
  RUST_TOOLCHAIN_VERSION: "nightly"

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Use shared Rust toolchain setting up steps
        uses: ./.github/actions/toolchain-shared
        with:
          rust_toolchain_version: ${{ env.RUST_TOOLCHAIN_VERSION }}

      - name: Use shared OCaml setting up steps
        uses: ./.github/actions/ocaml-shared
        with:
          ocaml_version: ${{ env.OCAML_VERSION }}

      - name: Build Rust Documentation
        run: |
          eval $(opam env)
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc --all --no-deps

      - name: Build the mdbook
        run: |
          eval $(opam env)
          cd book
          make deps
          make build

      - name: Arrange website folder hierarchy
        run: |
          mv ./target/doc ./book/book/html/rustdoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/html
